<?php
namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{

    /**
     * Retourne la liste des derniers projets signés
     *
     * @param string $alias
     * @param int $limit
     * @return array
     */
    public function getLastSignedProjects($alias = 'pj', $limit = 10)
    {
        return $this->createQueryBuilder($alias)
            ->where("$alias.active = TRUE")
            ->orderBy($alias . '.beginAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    /**
     * Retourne la liste des plus gros clients
     *
     * @param string $alias
     * @param int $limit
     * @return array
     */
    public function getTopClient($alias = 'pj', $limit = 10)
    {
        return $this->createQueryBuilder($alias)
            ->where($alias.'.active = TRUE')
            ->orderBy($alias . '.beginAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
}
