<?php
namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{

    public function getLastSignedProjects($alias = 'pj', $limit = 10)
    {
        return $this->createQueryBuilder($alias)
            ->where("$alias.active = TRUE")
            ->orderBy($alias . '.beginAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    

    public function getTopClient() {
        return $this->createQueryBuilder($alias)
        ->where("$alias.active = TRUE")
        ->orderBy($alias . '.beginAt', 'DESC')
        ->setMaxResults($limit)
        ->getQuery()
        ->getResult();
    }
}
