<?php
namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TechnologyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnologyRepository extends EntityRepository
{

    /**
     * Retourne la liste des technos embarquées
     *
     * @param string $alias
     * @param int $limit
     * @return array
     */
    public function getTechnos($alias = 'techno', $limit = 15)
    {
        return $this->createQueryBuilder($alias)
            ->select($alias . '.name, SUM(1)')
            ->leftJoin($alias . '.projects', 'p')
            ->where('p.active = true')
            ->groupby($alias . '.name')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    /**
     * Retourne la liste des technos les plus signées
     *
     * @param string $alias
     * @param int $limit
     * @return array
     */
    public function getMostSignedTechnos($alias = 'techno', $limit = 10)
    {
        return $this->createQueryBuilder($alias)
            ->select($alias . '.name, SUM(p.sellPrice)')
            ->leftJoin($alias . '.projects', 'p')
            ->where('p.active = true')
            ->groupby($alias . '.name')
//             ->orderby('sum')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
}
